export default iconList = [
	{
	  name : "fourneau",
	  url: '/trb-map/blastFurnaceIcon.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 45],
	  displayed : true,
	},
	{
	  name : "acierie",
	  url: '/trb-map/acierie.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	{
	  name : "aluminium",
	  url: '/trb-map/aluminium.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	{
	  name : "tth",
	  url: '/trb-map/tth.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	{
	  name : "cimenterie",
	  url: '/trb-map/cimenterie.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	{
	  name : "fonderie",
	  url: '/trb-map/fonderie.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	{
	  name : "ferroalliage",
	  url: '/trb-map/ferroalliage.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
	 {
	  name : "cokerie",
	  url: '/trb-map/cimenterie.png',
	  size: [71, 71],
	  origin: [0, 0],
	  anchor: [17, 34],
	  scaledSize: [25, 25],
	  displayed : true,
	},
]

    